//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginScribens.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginScribens.UI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string Common_Month {
            get {
                return ResourceManager.GetString("Common.Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        internal static string Common_Year {
            get {
                return ResourceManager.GetString("Common.Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Language_French {
            get {
                return ResourceManager.GetString("Language.French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Scribens.
        /// </summary>
        internal static string Ribbon_CloseTaskPane {
            get {
                return ResourceManager.GetString("Ribbon.CloseTaskPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string Ribbon_CorrectionModeButton {
            get {
                return ResourceManager.GetString("Ribbon.CorrectionModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Language.
        /// </summary>
        internal static string Ribbon_LanguageLabel {
            get {
                return ResourceManager.GetString("Ribbon.LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Sentence.
        /// </summary>
        internal static string Ribbon_LongSentenceModeButton {
            get {
                return ResourceManager.GetString("Ribbon.LongSentenceModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundancy.
        /// </summary>
        internal static string Ribbon_RedundancyModeButton {
            get {
                return ResourceManager.GetString("Ribbon.RedundancyModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformulation.
        /// </summary>
        internal static string Ribbon_ReformulationModeButton {
            get {
                return ResourceManager.GetString("Ribbon.ReformulationModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Ribbon_SettingsButton {
            get {
                return ResourceManager.GetString("Ribbon.SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Ribbon_ShowTaskPaneButton {
            get {
                return ResourceManager.GetString("Ribbon.ShowTaskPaneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string Ribbon_ShowUserAccountButton {
            get {
                return ResourceManager.GetString("Ribbon.ShowUserAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjectivity Negative.
        /// </summary>
        internal static string Ribbon_SubjectivityNegativeModeButton {
            get {
                return ResourceManager.GetString("Ribbon.SubjectivityNegativeModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjectivity Positive.
        /// </summary>
        internal static string Ribbon_SubjectivityPositiveModeButton {
            get {
                return ResourceManager.GetString("Ribbon.SubjectivityPositiveModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary Enhancement.
        /// </summary>
        internal static string Ribbon_VocabularyEnhancementModeButton {
            get {
                return ResourceManager.GetString("Ribbon.VocabularyEnhancementModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Reduction.
        /// </summary>
        internal static string Ribbon_WordReductionModeButton {
            get {
                return ResourceManager.GetString("Ribbon.WordReductionModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow background checking.
        /// </summary>
        internal static string SettingsWindow_AllowBackgroundChecking {
            get {
                return ResourceManager.GetString("SettingsWindow.AllowBackgroundChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string SettingsWindow_BackgroundChecking {
            get {
                return ResourceManager.GetString("SettingsWindow.BackgroundChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SettingsWindow_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check every.
        /// </summary>
        internal static string SettingsWindow_CheckInterval {
            get {
                return ResourceManager.GetString("SettingsWindow.CheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        internal static string SettingsWindow_CheckIntervalUnit {
            get {
                return ResourceManager.GetString("SettingsWindow.CheckIntervalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Settings.
        /// </summary>
        internal static string SettingsWindow_PersonalSettingsHeader {
            get {
                return ResourceManager.GetString("SettingsWindow.PersonalSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string SettingsWindow_Save {
            get {
                return ResourceManager.GetString("SettingsWindow.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Premium account has expired.
        /// </summary>
        internal static string TaskPane_AccountExpired {
            get {
                return ResourceManager.GetString("TaskPane.AccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct all issues.
        /// </summary>
        internal static string TaskPane_ApplyAll {
            get {
                return ResourceManager.GetString("TaskPane.ApplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to correct your spelling.
        /// </summary>
        internal static string TaskPane_ApplySolutionButtonToolTip {
            get {
                return ResourceManager.GetString("TaskPane.ApplySolutionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy a Premium subscription.
        /// </summary>
        internal static string TaskPane_BuySubscription {
            get {
                return ResourceManager.GetString("TaskPane.BuySubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        internal static string TaskPane_Checking {
            get {
                return ResourceManager.GetString("TaskPane.Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your text exceeds the number of characters allowed..
        /// </summary>
        internal static string TaskPane_ExceedLimitCharacters {
            get {
                return ResourceManager.GetString("TaskPane.ExceedLimitCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial version has expired.
        /// </summary>
        internal static string TaskPane_ExceedTrial {
            get {
                return ResourceManager.GetString("TaskPane.ExceedTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore all issues.
        /// </summary>
        internal static string TaskPane_IgnoreAll {
            get {
                return ResourceManager.GetString("TaskPane.IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore this correction.
        /// </summary>
        internal static string TaskPane_IgnoreCorrection {
            get {
                return ResourceManager.GetString("TaskPane.IgnoreCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues found.
        /// </summary>
        internal static string TaskPane_IssuesFound {
            get {
                return ResourceManager.GetString("TaskPane.IssuesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues found.
        /// </summary>
        internal static string TaskPane_NoIssuesFound {
            get {
                return ResourceManager.GetString("TaskPane.NoIssuesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Suggestion.
        /// </summary>
        internal static string TaskPane_NoSuggestion {
            get {
                return ResourceManager.GetString("TaskPane.NoSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the Premium version to benefit from all the advantages of Scribens.
        /// </summary>
        internal static string TaskPane_Subscribe {
            get {
                return ResourceManager.GetString("TaskPane.Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribens.
        /// </summary>
        internal static string TaskPane_Title {
            get {
                return ResourceManager.GetString("TaskPane.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become Premium.
        /// </summary>
        internal static string UserInfoPane_BecomePremium {
            get {
                return ResourceManager.GetString("UserInfoPane.BecomePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string UserInfoPane_Clear {
            get {
                return ResourceManager.GetString("UserInfoPane.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string UserInfoPane_Connect {
            get {
                return ResourceManager.GetString("UserInfoPane.Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string UserInfoPane_Email {
            get {
                return ResourceManager.GetString("UserInfoPane.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Date:.
        /// </summary>
        internal static string UserInfoPane_ExpiredDate {
            get {
                return ResourceManager.GetString("UserInfoPane.ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to my account.
        /// </summary>
        internal static string UserInfoPane_Login {
            get {
                return ResourceManager.GetString("UserInfoPane.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is inactived.
        /// </summary>
        internal static string UserInfoPane_Message_InactiveAccount {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account.
        /// </summary>
        internal static string UserInfoPane_Message_InvalidAccount {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.InvalidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown error occurred when login. Please check the log file.
        /// </summary>
        internal static string UserInfoPane_Message_LoginUnknownError {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.LoginUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining days.
        /// </summary>
        internal static string UserInfoPane_Message_RemainingDays {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.RemainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining months.
        /// </summary>
        internal static string UserInfoPane_Message_RemainingMonths {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.RemainingMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining years.
        /// </summary>
        internal static string UserInfoPane_Message_RemainingYears {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.RemainingYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribens is in use by another user.
        /// </summary>
        internal static string UserInfoPane_Message_SessionActive {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.SessionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        internal static string UserInfoPane_Message_SignOutConfirm {
            get {
                return ResourceManager.GetString("UserInfoPane.Message.SignOutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string UserInfoPane_MyAccount {
            get {
                return ResourceManager.GetString("UserInfoPane.MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string UserInfoPane_Password {
            get {
                return ResourceManager.GetString("UserInfoPane.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string UserInfoPane_SignOut {
            get {
                return ResourceManager.GetString("UserInfoPane.SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription:.
        /// </summary>
        internal static string UserInfoPane_Subscription {
            get {
                return ResourceManager.GetString("UserInfoPane.Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string UserInfoPane_Subscription_Expired {
            get {
                return ResourceManager.GetString("UserInfoPane.Subscription.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not existed.
        /// </summary>
        internal static string UserInfoPane_Subscription_NotExist {
            get {
                return ResourceManager.GetString("UserInfoPane.Subscription.NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string UserInfoPane_Subscription_Trial {
            get {
                return ResourceManager.GetString("UserInfoPane.Subscription.Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium 1 year.
        /// </summary>
        internal static string UserInfoPane_SubscriptionType_P1A {
            get {
                return ResourceManager.GetString("UserInfoPane.SubscriptionType_P1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium 1 month.
        /// </summary>
        internal static string UserInfoPane_SubscriptionType_P1M {
            get {
                return ResourceManager.GetString("UserInfoPane.SubscriptionType_P1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium 3 months.
        /// </summary>
        internal static string UserInfoPane_SubscriptionType_P3M {
            get {
                return ResourceManager.GetString("UserInfoPane.SubscriptionType_P3M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UserInfoPane_UserName {
            get {
                return ResourceManager.GetString("UserInfoPane.UserName", resourceCulture);
            }
        }
    }
}
